CREATE TABLE MOVIES(
	Id VARCHAR(20) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Year INT(11) NOT NULL,
	Runtime INT(11) NOT NULL,
	rating DECIMAL(2,1),
	Plot VARCHAR(1000),
	Budget INT(11),
	Gross_glob BIGINT(13),
	Submitter_id VARCHAR(10),
	UNIQUE (Name),
	PRIMARY KEY (Id)
);

CREATE TABLE ACTORS(
	Id VARCHAR(20) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Gender CHAR(1) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE DIRECTORS(
	Id VARCHAR(20) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE DIRECTORS_GENRES(
	Director_id VARCHAR(20) NOT NULL,
	Genre VARCHAR(255) NOT NULL,
	PRIMARY KEY (Director_id,Genre),
	FOREIGN KEY (Director_id) REFERENCES DIRECTORS(Id) ON DELETE CASCADE
);

CREATE TABLE MOVIE_DIRECTORS(
	Director_id VARCHAR(20) NOT NULL,
	Movie_id VARCHAR(20) NOT NULL,
	PRIMARY KEY (Director_id,Movie_id),
	FOREIGN KEY (Director_id) REFERENCES DIRECTORS(Id) ON DELETE CASCADE,
	FOREIGN KEY (Movie_id) REFERENCES MOVIES(Id) ON DELETE CASCADE
);

CREATE TABLE ROLES(
	Role VARCHAR(255) NOT NULL,
	Actor_id VARCHAR(20) NOT NULL,
	Movie_id VARCHAR(20) NOT NULL,
	PRIMARY KEY (Role,Actor_id,Movie_id),
	FOREIGN KEY (Actor_id) REFERENCES ACTORS(Id) ON DELETE CASCADE,
	FOREIGN KEY (Movie_id) REFERENCES MOVIES(Id) ON DELETE CASCADE
);

CREATE TABLE REVIEWS(
	Reviewer_id VARCHAR(50) NOT NULL,
	Movie_id VARCHAR(20) NOT NULL,
	Rating INT(11) NOT NULL,
	Date DATETIME NOT NULL,
	Review_text VARCHAR(6000) NOT NULL,
	PRIMARY KEY (Reviewer_id,Movie_id),
	FOREIGN KEY (Movie_id) REFERENCES MOVIES(Id) ON DELETE CASCADE
);

CREATE TABLE MOVIE_GENRES(
	Movie_id VARCHAR(20) NOT NULL,
	Genre VARCHAR(255) NOT NULL, 
	PRIMARY KEY (Genre,Movie_id),
	FOREIGN KEY (Movie_id) REFERENCES MOVIES(Id) ON DELETE CASCADE
);